### ISSUE TITLE
Client / Server trait tweaks

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/http-types#120]
I was thinking we should do the following:

- Rename the main methods should be renamed to `Server::respond` and `Client::request`.
- The argument passed to both methods should be `impl Into<Request>`.

That should set us up better for using Surf to construct requests that can be passed into Tide.

**Comment by yoshuawuyts** [comment]
Also if we return `Into<Response>` we could get rid of this line here: https://docs.rs/tide/0.8.0/src/tide/server/mod.rs.html#338 and rewrite the `Err` case using `unwrap_or_else`.

**Comment by yoshuawuyts** [comment]
oh, `Into<Response>` prevents making this a trait object.

**Comment by Fishrock123** [comment]
This can be closed, yeah? Idk why github didn't do it automatically.
