### ISSUE TITLE
Add support for responding with multiple responses for push

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/http-types#136]
http/2 introduced a mechanism for sending back multiple responses for a single request (PUSH frames). This is often used as an optimization for requesting static files in the browser, so for when example a user requests `index.html` we send back `bundle.css` and `bundle.wasm` as well because we *know* that those will be requested next.

This mechanism is not limited to http/2, http/3 makes use of it as well. And as such it makes sense to introduce a mechanism for sending back multiple responses into `http-types` since it's part of the HTTP semantics now.

## API example
In https://github.com/http-rs/http-types/issues/126#issuecomment-629650395 I authored an example for multipart responses, which are "multiple bodies sent in response to a single request". HTTP push is "multiple responses sent in response to a single request". So I was thinking we could make it a similar-ish API, but multiplex on the response level rather than on the request level. This is a sketch

```rust
let mut res = Response::new(200);
res.set_body(Body::from_file("assets/index.html").await?);

// provide a way to do feature detection. Knowing the http version probably works well enough.
if req.version() >= http_types::Version::2_0 {
    // we should send over fully-qualified HTTP responses.
    let mut css = Response::new(200);
    css.set_body(Body::from_file("assets/bundle.css").await?);
    // in order to push we need to share which URL this resource would live at.
    res.push("bundle.css", css);

    let mut wasm = Response::new(200);
    wasm.set_body(Body::from_file("assets/bundle.wasm").await?);
    res.push("bundle.wasm", wasm);
}

// provide some way to iterate over the pushed responses
for pushed in res.pushed() {
    println!("{}", pushed.url());
}
```

## alternatives

Something that's been brought up before is to use a channel based approach provided by `request` instead. I think the right mental model for push is: "multiple responses to a single request" and we should create an API that matches that. And *actually* sending back multiple responses in response to a request is the clearest way to model that.

**Comment by Fishrock123** [comment]
Does it make more sense to push multiple `Response`s to a _connection_, rather than append to one main response? (I'm not really familiar with how http/2/3 deal with status codes and headers.)

If so, we probably want to think more about Tide's route/middleware return type.

**Comment by yoshuawuyts** [comment]
> Does it make more sense to push multiple Responses to a connection, rather than append to one main response?

The HTTP/2 impl should take care of this. The `http-types` crate provides a way to interface with this, but it's up to the backing impl to correctly handle this. This is similar to `upgrade` headers and `trailers` -- they too deal with sending bytes over the wire but all `http-types` does is provide an interface to build that out.

**Comment by yoshuawuyts** [comment]
HTTP/2 PUSH appears to be effectively have been phased out with Chrome having announced they're going to deprecate support for this. It doesn't seem particularly pressing to support this at the time of writing.
