### ISSUE TITLE
No way to access value of a mime::ParamValue

### ISSUE THREAD

**Issue by kyrias** [http-rs/http-types#149]
`mime::ParamValue` has a private tuple struct constructor and no accessor methods, so there's no way to actually get the value out of them.

**Comment by kyrias** [comment]
To give a bit of a more actionable comment, is the plan to implementing some kind of accessors for it, or can we just make the constructor public so that it's possible to pattern match on them?

**Comment by yoshuawuyts** [comment]
@kyrias could you say more? `ParamValue` implements `Display` which is a way to access the value contained in the inner `Cow<'static, str>` through a unified interface. But did you have something else in mind?

**Comment by kyrias** [comment]
Hm, didn't really think about `Display` since its generally for _output_ and you don't really have any specific guarantee that it'll be just the raw string value that it contains.  But I guess passing `format!("{}", foo)` should be fine in this case, yeah.
