### ISSUE TITLE
Request::query should match Tide's behavior

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/http-types#154]
In https://github.com/http-rs/tide/pull/537 we couldn't update the `Request::query` method to `http_types`' version because tests were failing. We should port Tide's tests to `http-types` and fix the query method to match the behavior. This means correctly parsing empty query strings, and setting a 400 status code.

This should be fairly straight forward, so marking as a good first issue!

## Refs
- Tide tests: https://github.com/http-rs/tide/blob/master/tests/querystring.rs
- Request::query: https://docs.rs/http-types/2.0.1/http_types/struct.Request.html#method.query

**Comment by plippe** [comment]
Hey;

Happy to give it a try.

**Comment by plippe** [comment]
@yoshuawuyts would you mind releasing a new version of http-types with my changes. That would allow me to update tide.

**Comment by Fishrock123** [comment]
@plippe We'll probably do that tomorrow or so - Yosh mentioned doing a tide 0.10.0 tomorrow, which we would want a new http-types release for.

In the mean time, you can make a test/dev branch by updating tide's `Cargo.toml` to:
```
http-types = { git = "https://github.com/http-rs/http-types.git" }
```

if you made a draft branch that would probably help us do the update!
