### ISSUE TITLE
Status should take TryInto<StatusCode>

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/http-types#155]
When writing code quickly it's nice to be able to quickly jot down statuscodes for errors. It'd be nice if the Status trait was able to accept a wider range of input.

```rust
// current
let bar = foo.status(StatusCode::NotFound)?;

// proposed
let bar = foo.status(404)?;
```

We already do this in the Response constructor as well. This should provide a template for how to go about it. Marking as a good first issue!

**Comment by zeroed** [comment]
Hello.

Thank you for opening and labelling `good-first-issues`; I would be glad to work on this.
