### ISSUE TITLE
Expose method shorthands for Request constructor

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/http-types#156]
In Surf creating new requests and responses is really straightforward. It'd be nice if we were able to expose shorthands from http-types as well.

```rust
// current
let req = Request::new(Method::Get, Url::parse("https://foo.biz").unwrap());

// with this proposal
let req = Request::get(Url::parse("https://foo.biz").unwrap());

// once the TryFrom patch on the url crate is published
let req = Request::get("https://foo.biz");
```

The downside is that this will add more methods to the `Request` type. But we already have many methods, and these feel fairly natural as constructors. I would propose we add them.

Marking as "good first issue" because this should be fairly straightforward. The bounds should be copied from the `Request::new` method, forwarding to `Request::new` internally. Thanks!

**Comment by zeroed** [comment]
Hello,
thank you for opening and labelling `good-first-issues`; I would be glad to propose a very simple approach to your suggestion and extend the test suite with examples as well .
