### ISSUE TITLE
Design proposal: Add some sort of `canceled` flag to Request

### ISSUE THREAD

**Issue by jbr** [http-rs/http-types#161]
This would touch tide and possibly async-h1 as well. The idea proposed by @jdortiz in discord was for tide to support connection cancellation in order to early-return from the middleware-response handler stack

**Comment by jbr** [comment]
### implementation thoughts

This probably would be more complex than just adding a bool to Request, since either tide's Server::listen() loop or async-h1 would need to be able to notice that the TcpStream had been disconnected and update this aspect of the request state from elsewhere without owning the Request. It might be as simple as an Arc<AtomicBool> on Request that's cloned in the listen loop and set from a task spawned to wait for TcpStream cancelation

**Comment by Fishrock123** [comment]
Wouldn't this be better as a set of methods?

i.e. `cancel()` and `was_canceled()` or something?

**Comment by Fishrock123** [comment]
Another idea might be the ability to get the `TcpStream` itself from a Request/Response - although in the case of e.g. http3 that would no longer be a `TcpStream`.

**Comment by jbr** [comment]
Yeah, I imagine that in addition to storing the canceled state on a Request we’d also want a setter and getter for that state

**Comment by jbr** [comment]
It might be sufficient to put a Box<dyn clone of the IO (AsyncRead+AsyncWrite+Clone)> on the Request and let anyone with cancelation concerns write their own middleware for custom behavior

**Comment by yoshuawuyts** [comment]
@jbr I'm not sure I follow the motivation for this proposal. I thought we already supported early returns in middleware by omitting the call to `next().await` but I'm probably missing something. An example would be useful here.

**Comment by jbr** [comment]
If I understand the use case @jdortiz described in discord, this would be used within a long-running async endpoint. A scenario might be an endpoint that makes a bunch of external requests (or database calls, or calculations, etc), but if the connection is closed, they'd like to early-return. It seems like a fairly uncommon use case and I've personally never used or seen something like this, but I thought I'd write an issue anyway for discussion. If I understand this proposal, the endpoint code would look like

```rust
async fn takes_a_while(request: Request<()>) -> Result {
  let result1 = expensive_call_1().await;
  if request.canceled() { return Err(/*whatever, it's ignored*/) }
  let result2 = expensive_call_2(result1).await
  …
}
```

**Comment by yoshuawuyts** [comment]
I'm confused why "cancelled" should ride as part of the `request`. If this is user code then various strategies could be applied: returning a flag from a function, setting a `task_local` value, returning an error, or using a [stop-token](https://github.com/async-rs/stop-token). This feels like a general (async) control-flow question that's not specific to HTTP, so I'm inclined to wait and see if this can be resolved in user code first.

**Comment by jbr** [comment]
Makes sense to me. The only concern I can see with that is how the user code finds out that the transport / io read zero bytes (indicating closure), but concur this is not a common or essential problem for web frameworks to solve
