### ISSUE TITLE
Consider using u64 for Body length

### ISSUE THREAD

**Issue by VShell** [http-rs/http-types#164]
Currently, the Body's length is usize - which implies that a 32-bit web server could only respond with 4GB of data without using chunked encoding, even if they're streaming data which could be much larger. This could be resolved by using a u64 instead.

**Comment by yoshuawuyts** [comment]
Ah yeah, we should consider this change for `http-types@3`. [`fs::Metadata::len`](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.len) returns a u64 as well.
