### ISSUE TITLE
EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by sankar-boro** [http-rs/http-types#177]
_req.take_body().into_json().await?

on using above syntax while parsing body gives "EOF while parsing a value at line 1 column 0 error".
Please look into it and fix the error.

**Comment by yoshuawuyts** [comment]
@sankar-boro thanks for opening this issue. Do you have a repro we could check out? We haven't encountered this issue before, and it'll be hard to say more about this issue without more information. Thanks!

**Comment by sankar-boro** [comment]
Thanks for the reply.

Link for issue test on github.
https://github.com/sankar-boro/test-server
