### ISSUE TITLE
Authorization Header Parsing

### ISSUE THREAD

**Issue by naftulikay** [http-rs/http-types#181]
I'm currently working on a demo project using [`tide`](https://github.com/http-rs/tide) to demo JWT authorization. It's not open source yet but it probably will be.

Looking at [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization), the structure of the `Authorization` header consists of `<type> <credentials>`, so in my app, I modeled this with the following struct.

```rust
pub enum AuthorizationKind<'a> {
    Basic,
    // ...
    Unknown(&'a str), // borrowed reference to the underlying `HeaderValue`
}

pub struct AuthorizationData<'a> {
    pub kind: Option<AuthorizationKind<'a>>,
    pub data: &'a str,
}
```

This model allows most use-cases that I can think of, even outside of what is recommended, `<type>` can be omitted such that there's no authorization type present in the header, e.g. `Authorization: BUGU93VSw-mUi5-d0WNPq0JjXdMt2Ls7unnX4GuLNtg`.

All of this can be done zero-copy as far as I can tell by just referencing ranges in the internal `HeaderValue`.

I'm implementing this in my own demo codebase and I realized this is probably useful to a _lot_ of people beyond me, so I'm wondering if I can contribute this to this library.

Would such an addition be considered, or is this outside of the range of what `http-types` wants to be?

**Comment by Fishrock123** [comment]
See https://github.com/http-rs/http-types/issues/99

**Comment by yoshuawuyts** [comment]
We now have an [`auth` submodule](https://docs.rs/http-types/2.9.0/http_types/auth/index.html) which contains the base headers for authorization.
