### ISSUE TITLE
Querystrings don't support leading `&` and `&&` in-between other pairs anymore

### ISSUE THREAD

**Issue by rkusa** [http-rs/http-types#184]
Since c87c466ffdb26da998c2d612cb0c601413c7a6e8 (using `serde_qs` for querystring parsing) the following querystrings are not parsed anymore:
- `http://example.com/?&msg=Hello`
- ~~`http://example.com/?msg=Hello&`~~ (Edit: my bad, still works)
- `http://example.com/?foo=bar&&msg=Hello`

`req.query()` fails with `missing field msg` for all of them.

If I understand [the spec](https://url.spec.whatwg.org/#urlencoded-parsing) correctly, a `&` at the start, at the end, or an `&&` should be perfectly fine. Those empty byte sequences after splitting by `&` are just ignored.

**Comment by jbr** [comment]
This seems like a serde_qs issue, since parsing querystrings is that crate's entire purpose.  Using serde_urlencode does not support decoding nested structures like hashmaps and arrays, which although not part of `x-www-form-urlencoded` are commonly used

**Comment by rkusa** [comment]
I've proposed a fix to `serde_qs` here https://github.com/samscott89/serde_qs/pull/31

**Comment by rkusa** [comment]
I am wondering whether `http-types` should have some basic `req.query()` tests, to prevent possible regressions in the future (and maybe because `serde_qs` itself does not seem to have a CI in-place - which could be solved by contributing a copy of `http-types`' Github workflow to it)?

**Comment by jbr** [comment]
This might be a good start: https://github.com/http-rs/tide/commit/c282e92ed9a1a76dec17066daef77543fafa3ebf

**Comment by rkusa** [comment]
The `serde_qs` fix was published as `0.6.1`. There is no need to bump the version in [http-types Cargo.toml](https://github.com/http-rs/http-types/blob/master/Cargo.toml#L43) since the "0.6.0" pattern includes bugfix releases, right?

**Comment by jbr** [comment]
Yeah, running `cargo update` on a project with only tide master uses serde_qs 0.6.1

**Comment by rkusa** [comment]
Cool! I'll be so free to close the issue then 👍
