### ISSUE TITLE
Body::from_file should actually be Body::from_path, and Body::from_file should take a File

### ISSUE THREAD

**Issue by jbr** [http-rs/http-types#185]

**Comment by brightly-salty** [comment]
Hey, quick question. While implementing this, I realized we can use either `std::fs::File` or `async_std::fs::File` as the field. Which one should we use, or is there a third trait that is implemented for both of them that will work?
Thanks

**Comment by joshtriplett** [comment]
See also https://github.com/http-rs/http-types/pull/318#issuecomment-766195364

**Comment by joshtriplett** [comment]
Fixed in https://github.com/http-rs/http-types/pull/318 .
