### ISSUE TITLE
Add serde support for Url (and maybe others?)

### ISSUE THREAD

**Issue by zkat** [http-rs/http-types#205]
It would be really great if `Url` itself supported serde.

**Comment by jbr** [comment]
Totally agreed, but I think that would have to be a pr to https://github.com/servo/rust-url, since http-types is just reexporting that: https://github.com/http-rs/http-types/blob/master/src/lib.rs#L110-L115

**Comment by zkat** [comment]
https://github.com/servo/rust-url/blob/master/src/lib.rs#L2422-L2434 it already supports it. I think http-types just needs to forward the feature appropriately??
