### ISSUE TITLE
Make async-std dependency optional

### ISSUE THREAD

**Issue by akhilles** [http-rs/http-types#244]
Hello! Would it be possible to make the `async-std` dependency optional and feature-gated? Currently, `async-std` is used for the following: `async_std::io` traits, `async_std::sync::channel`, and `async_std::fs`. If `futures-lite` and `async-channel` are used instead (NOTE: these are already dependencies for `async-std`, so no new dependencies would be added), a bunch of transitive dependencies would be removed without sacrificing any functionality.

`Cargo.lock` diff, with `default-features = false`, after making `async-std` optional: https://gist.github.com/akhilles/60d553d797f9e0e94056da3274285e31.
It's also a fairly straight-forward change: https://gist.github.com/akhilles/29a8de956cf7beb274a2f8d6959d8e4f

Feel free to close this if it doesn't align with this library's design goals.

**Comment by yoshuawuyts** [comment]
Hi, sure we can do this — but in order to not break the API we should enable it by default. A PR to add an `async-std` feature flag would be welcome!
