### ISSUE TITLE
Derive Serializable and Deserializable for http_types::method::Method

### ISSUE THREAD

**Issue by mfelsche** [http-rs/http-types#260]
We want to use `Method` as part of a config value, deserialized from yaml, in order to easily restrict values to what is supported as HTTP Method by libraries using this lib (e.g. tide and surf).

Currently we have to throw in some custom machinery to make use of the `FromStr` impl on `Method`, which is rather cumbersome (to me).

If nothing speaks against it, I can provide the necessary changes as a PR.

**Comment by yoshuawuyts** [comment]
@mfelsche that's a great idea; thanks for bringing it up. Probably adding this to `StatusCode` and `Version`  would be useful as well -- that way we ensure all enums can be serialized.

> If nothing speaks against it, I can provide the necessary changes as a PR.

That would be most welcome!

**Comment by mfelsche** [comment]
Will do so in the coming days, including `StatusCode` and `Version`.
