### ISSUE TITLE
Remove http header re-exports from crate root

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/http-types#264]
We currently export the following headers from the crate root:

![Screenshot_2020-10-31 http_types - Rust(2)](https://user-images.githubusercontent.com/2467194/97778856-74889400-1b7a-11eb-8f9e-cad1af07c93d.png)

A majority of these are re-exports from our sub-modules. As our index is growing because of the addition of a variety of typed headers I would like to trim down some of these re-exports and leave them accessible only as part of the sub-modules. The types to keep would be only the types required to construct a request / response, or types that don't currently already have a dedicated submodule:

__keep__
- `Body` core type
- `Error` core type
- `Extensions` no dedicated submodule
- `Request` core type
- `Response` core type
- `Url` core type (for now; revisit after the `TryFrom` patch on `url` is published)

__move to submodule__
- `Cookie` has submodule, not critical
- `Headers` rarely referenced directly, and when used it's in conjunction with other `header` types
- `Mime` (rename to `MediaType` (see #251 )
- `Trailers` has a submodule and uncommonly used

**Comment by brightly-salty** [comment]
I'd be willing to attempt to implement this and submit a PR. Is this what is needed?
- remove `pub use crate::cookies::Cookie` from src/lib.rs
- remove `pub use mime::Mime` from src/lib.rs
- remove `pub use trailers::Trailers;` from src/lib.rs
- remove `pub use headers::Headers` from src/lib.rs

**Comment by yoshuawuyts** [comment]
@brightly-salty yes indeed!

**Comment by joshtriplett** [comment]
Fixed by #305.
