### ISSUE TITLE
Remove Clone from StatusCode

### ISSUE THREAD

**Issue by Fishrock123** [http-rs/http-types#323]
Mentioned in https://github.com/http-rs/http-types/pull/319#issuecomment-761530241 `StatusCode` is `Clone`, but it's also `Copy`, as it is just a wrapper around `u16`. I think we should remove `Clone` from it since it doesn't really make sense.

**Comment by yoshuawuyts** [comment]
`Copy` has a requirement on `Clone`. It's defined as:
```rust
pub trait Copy: Clone { }
```
We can't remove `Clone` for that reason.
