### ISSUE TITLE
StatusCode::Forbidden (403) has the description of StatusCode::NotFound (404)

### ISSUE THREAD

**Issue by Bauke** [http-rs/http-types#350]
Noticed this just now: [docs.rs link]

[docs.rs link]: https://docs.rs/http-types/2.10.0/http_types/enum.StatusCode.html#variant.Forbidden

**Comment by yoshuawuyts** [comment]
Ha, good catch! -- this must've been an issue copy-pasting the docs.

**Comment by joshtriplett** [comment]
This was fixed in https://github.com/http-rs/http-types/pull/341 , which will go into http-types 3, but it hasn't yet been released in a 2.x stable version.

**Comment by Fishrock123** [comment]
This was fixed and released in 2.11.0
