### ISSUE TITLE
trace context randomness

### ISSUE THREAD

**Issue by alexwennerberg** [http-rs/http-types#357]
The `rand` crate generates cryptographically secure random numbers. As a result, it is slower, slower to build, and has a larger dependency tree. To my understanding of the Trace Context spec (https://www.w3.org/TR/trace-context/#privacy-of-traceparent-field), cryptographic security is not necessary for this field. This library can replace `rand` with a simpler crate, like `fastrand`: https://crates.io/crates/fastrand

Let me know what you think!

**Comment by Fishrock123** [comment]
Merged: https://github.com/http-rs/http-types/pull/358
