### ISSUE TITLE
Add `Prefer` header

### ISSUE THREAD

**Issue by Fishrock123** [http-rs/http-types#366]
See https://datatracker.ietf.org/doc/html/rfc7240
And also mentioned in https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#75-standard-request-headers

- [ ] Add `Prefer` to `constants`
- [ ] Add a typed header for `Prefer`

**Comment by yoshuawuyts** [comment]
yess, thanks! - now tracking this in the http headers GH Project as: https://github.com/http-rs/http-types/issues/469
