### ISSUE TITLE
Change signature of `Headers::{append,insert}`

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/http-types#383]
See https://github.com/http-rs/tide/issues/853

## Tasks
- [ ] change signature of `{Request,Response,Headers}::append` to return `Result`
- [ ] change signature of `{Request,Response,Headers}::insert` to return `Result`

**Comment by pepoviola** [comment]
Hi @yoshuawuyts, I can take a look unless you are already working on this.
Thanks!
