### ISSUE TITLE
Reconsider use of `url`

### ISSUE THREAD

**Issue by bluetech** [http-rs/http-types#77]
Hi, I am not a user of this crate, but I saw the announcement post. Please feel free to close this if you disagree.

---

In the post, you listed use of the `url::Url` type as an advantage of this crate. But I think it is not a good fit for such a library.

Semantically, the thing that goes in an HTTP request is *not* a `url::Url` (== WHATWG URL). It is a "Request Target" as defined by [RFC 7230](https://tools.ietf.org/html/rfc7230#section-5.3). They are of course related, but not interchangeable.

Some URLs are not valid Request Targets. For example, `ftp://foo/bar` is a valid `url::Url`, but obviously should not reach HTTP. But `Request::new()` accepts all `url`s without any verification. (There are many other examples).

Some Request Targets are not valid URLs. For example, `*` is a valid Request Target (see RFC) that is not a URL. (There are many other examples). But `async-h1::server::decode()` does `let uri = url::Url::parse(&format!("{}{}", addr, uri))?;` (where `uri` is `httparse::Request.path`) which will fail for such.

Also, the `hyperium::http` interop module has conversions between `url` and `http::Uri` but this will also run into trouble as described above.

I suspect this will cause you a lot of headache. My suggestion is to use a type which models a Request Target as described in the RFC and not use WHATWG URL which is really meant for browsers, not the wire. The `http::Uri` type does this correctly IMO, except for the name -- I would call it `RequestTarget` to avoid any and all confusion.

**Comment by yoshuawuyts** [comment]
Hi, thanks for opening this issue! As you have already guessed, we have given this some thought. For example `unix://foo/bar` could very well be HTTP. Or `docker://my/container` as well. We didn't want to constrain the protocol prefix inside `http-types`.

Also the decision to use WHATWG URLs is to follow Nodejs's server implementation which consideres non-WHATWG URLs to now be "deprecated" ([src](https://nodejs.org/api/url.html#url_legacy_url_api)). Afaik this is working out well for them, which inspired that this approach would work well for us.
